export const STATIC_PUBLICATIONS = [
  // 2026 - Under Review
  {
    year: 2026,
    status: 'Under Review',
    title: 'Unsupervised Clustering of Psychosocial Profiles for Patient Stratification in Spinal Pain Management',
    authors: 'Alemu Sisay Nigru, Federico Maffezzoni, Sergio Benini, Serena Miglio, Matteo Bonetti, Michele Frigerio, Graziella Bragaglio, Chiara D\'Adda, Riccardo Leonardi',
    journal: 'Under Review',
    highlights: [
      'Identified two distinct biopsychosocial phenotypes: Adaptive (60%) and Maladaptive (40%)—independent of structural pathology.',
      'Maladaptive phenotype marked by severe pain, high disability, reduced quality of life, and predominant avoidance coping.',
      'Four-variable screening tool accurately discriminates Maladaptive phenotype (AUC = 0.950) for mechanism-informed, stratified spine care.',
    ],
    abstract: 'Background Context: Chronic spinal pain is highly heterogeneous, and traditional anatomy-driven classifications fundamentally fail to capture the biopsychosocial factors that drive pain-related disability. Data-driven phenotyping is needed to facilitate stratified, mechanism-informed care. Purpose: To identify distinct biopsychosocial phenotypes in patients with chronic spinal pain and to develop and validate a brief, clinically feasible screening tool for phenotype identification. Study Design/Setting: Cross-sectional study conducted in an outpatient rehabilitation clinic, in Brescia, Italy. Patient Sample: The study sample comprised 129 patients with spinal pain. Outcome Measures: Self-report Measures: Pain intensity (PainNRS), functional disability (RMDS), quality of life (WHOQoL), and coping behaviors (COPENVI) were assessed. Physiologic Measures: Structural pathology was evaluated using MRI/CT findings, analyzed at the disc-level across 230 variables. Methods: K-means clustering was applied to twelve clinical and psychosocial variables to identify phenotypes. Cluster validity and stability were assessed using multiple internal validation techniques. Structural MRI/CT findings were used for external validation. Supervised predictive modeling was subsequently employed to derive a simplified screening tool for phenotype assignment. Results: Unsupervised clustering identified two stable, clinically distinct phenotypes: an Adaptive phenotype (60%) characterized by lower pain intensity, lower functional disability, adaptive coping, and higher quality of life; and a Maladaptive phenotype (40%) marked by severe pain intensity, high functional disability, reduced quality of life, and predominant avoidance coping. Network analysis demonstrated a densely interconnected psychosocial structure in the Maladaptive phenotype. No significant associations were observed between phenotype membership and structural pathology. A four-variable screening tool (Pain Intensity, Functional Disability, Psychological Quality of Life, Avoidance Coping) accurately discriminated the Maladaptive phenotype (AUC = 0.950). Conclusions: Two distinct biopsychosocial phenotypes of spinal pain were identified that are independent of structural pathology. Critically, these phenotypes differ not only in severity but in underlying psychosocial structure. The derived screening tool enables the translation of this phenotyping into clinical practice, supporting a move toward mechanism-informed, stratified spine care.',
    link: null,
  },
  {
    year: 2026,
    status: 'Under Review',
    title: 'Organization of Coping Strategies and Their Proximal Associations with Pain Intensity in Spinal Pain Patients',
    authors: 'Alemu Sisay Nigru, Federico Maffezzoni, Sergio Benini, Serena Miglio, Matteo Bonetti, Michele Frigerio, Graziella Bragaglio, Chiara D\'Adda, Riccardo Leonardi',
    journal: 'Under Review',
    highlights: [
      'Avoidance and Positive Attitude are the only coping dimensions independently associated with pain intensity, explaining 41.4% of variance.',
      'Other strategies (Social Support, Problem Orientation) relate to pain via indirect pathways through these proximal dimensions.',
      'Three coping profiles identified: Adaptive Copers (lowest pain), Moderate Copers, and Maladaptive Copers (highest pain).',
    ],
    abstract: 'Background: Although coping strategies are well-established psychological determinants of chronic pain, their relative importance and combined organization in relation to pain intensity remain unclear. Clarifying whether coping strategies act as independent correlates or as an organized system is essential for refining psychosocial assessment and intervention. Methods: In this cross-sectional study, 142 adults with spine-related pain completed the Cope-NVI assessing five coping dimensions. A multi-method analytical framework was applied: multiple regression identified independent associations with pain intensity, mediation analyses examined indirect pathways among coping strategies, and k-means clustering identified person-centered coping profiles. Results: Multiple regression identified Avoidance and Positive Attitude as the only coping dimensions independently associated with pain intensity, jointly explaining 41.4% of its variance. Mediation analyses demonstrated that other strategies, including Social Support and Problem Orientation, were related to pain primarily through indirect pathways via these proximal dimensions. Cluster analysis further validated this hierarchical structure, identifying three distinct coping profiles: Adaptive Copers (low Avoidance, high Positive Attitude; lowest pain), Moderate Copers, and Maladaptive Copers (high Avoidance, low Positive Attitude; highest pain). Conclusions: Coping strategies in spine-related pain are hierarchically organized in relation to pain intensity, with Avoidance and Positive Attitude functioning as central, proximal mechanisms. This framework helps explain inconsistent findings in prior coping research and supports psychosocial assessment and intervention strategies that prioritize these core dimensions within a person-centered approach.',
    link: null,
  },
  // 2025
  {
    year: 2025,
    status: 'Published',
    title: 'Rewiring Development in Brain Segmentation: Leveraging Adult Brain Priors for Enhancing Infant MRI Segmentation',
    authors: 'Alemu Sisay Nigru, Michele Svanera, Austin Dibble, Connor Dalby, Mattia Savardi, Sergio Benini',
    journal: 'arXiv preprint arXiv:2510.09306',
    highlights: [
      'LODi framework transfers anatomical knowledge from adult brain MRI to infant scans via transfer learning and domain adaptation.',
      'Pre-trained on 27k adult scans; adapted to 0–2 year-old population using weakly supervised learning with Infant FreeSurfer labels.',
      'Outperforms traditional supervised and domain-specific models on internal and external datasets; robust to motion artifacts.',
    ],
    abstract: 'Accurate segmentation of infant brain MRI is critical for studying early neurodevelopment and diagnosing neurological disorders. Yet, it remains a fundamental challenge due to continuously evolving anatomy of the subjects, motion artifacts, and the scarcity of high-quality labeled data. In this work, we present LODi, a novel framework that utilizes prior knowledge from an adult brain MRI segmentation model to enhance the segmentation performance of infant scans. Given the abundance of publicly available adult brain MRI data, we pre-train a segmentation model on a large adult dataset as a starting point. Through transfer learning and domain adaptation strategies, we progressively adapt the model to the 0-2 year-old population, enabling it to account for the anatomical and imaging variability typical of infant scans. The adaptation of the adult model is carried out using weakly supervised learning on infant brain scans, leveraging silver-standard ground truth labels obtained with FreeSurfer. By introducing a novel training strategy that integrates hierarchical feature refinement and multi-level consistency constraints, our method enables fast, accurate, age-adaptive segmentation, while mitigating scanner and site-specific biases. Extensive experiments on both internal and external datasets demonstrate the superiority of our approach over traditional supervised learning and domain-specific models. Our findings highlight the advantage of leveraging adult brain priors as a foundation for age-flexible neuroimaging analysis, paving the way for more reliable and generalizable brain MRI segmentation across the lifespan.',
    link: 'https://arxiv.org/pdf/2510.09306',
  },
  {
    year: 2025,
    status: 'Published',
    title: 'Toward a Clinically Integrated AI Framework for Personalized Spine Care',
    authors: 'Alemu Sisay Nigru, Sergio Benini, Yao Wang, Federico Maffezzoni, Matteo Bonetti, Michele Frigerio, Graziella Bragaglio, Serena Miglio, R Leonardi',
    journal: 'Available at SSRN 5860785',
    highlights: [
      'Modular AI framework unifies imaging analysis, patient-reported outcomes, and clinical reasoning in a single ecosystem.',
      'Three modules: automated imaging grading with radiologist-in-the-loop, multimodal PROM assessment, and LLM-based report generation.',
      'Proof-of-concept shows combining AI imaging findings with PROMs can shift treatment recommendations beyond imaging alone.',
    ],
    abstract: 'Background and Objective: Low back pain remains the leading global cause of disability and is driven by a multifactorial interplay of structural, clinical, behavioral, and psychosocial factors. Although artificial intelligence has demonstrated strong potential in spine imaging and outcome prediction, existing solutions are typically single-purpose and do not reflect this complexity. This work proposes a modular artificial intelligence framework designed to unify imaging analysis, patient-reported outcomes, and clinical reasoning within a single, clinically deployable ecosystem. Methods: We developed a conceptual architecture comprising three integrated modules:(1) an automated imaging analysis and severity grading system with radiologist-in-the-loop validation through a dedicated user interface;(2) a multimodal assessment engine incorporating patient-reported outcomes such as pain intensity, disability score, quality-of-life scores, coping strategies, as well as demographic and clinical factors; and (3) a language-generation module based on large language models for synthesizing imaging findings and patient-reported data into editable radiology reports and personalized clinical considerations. The design emphasizes security, interpretability, human-centered interfaces, and interoperability with existing hospital systems. Results: To explore the feasibility of integrating patient-reported outcome measures (PROMs) with AI-assisted imaging assessment for personalized treatment planning, a small proof-of-concept analysis was conducted using real-world patient data. Three representative patients with distinct psychosocial profiles were examined to demonstrate how combining AI-generated imaging findings with structured PROMs can shift treatment recommendations beyond what imaging alone would suggest. These illustrative cases showcase the practical potential of augmenting automated radiology reports with patient-reported contextual data to better guide individualized clinical management. This analysis is provided as supplementary material to demonstrate feasibility rather than to draw quantitative conclusions. Conclusions: The proposed framework outlines a clear pathway toward a comprehensive, multimodal AI decision-support ecosystem for spine care. By unifying imaging analysis, patient-reported measures, and AI-assisted reporting, it highlights how modular architectures can better reflect the biopsychosocial nature of LBP and support future clinical translation. The proof-of-concept findings provide initial evidence of feasibility and motivate subsequent large-scale validation.',
    link: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5860785',
  },
  // 2024
  {
    year: 2024,
    status: 'Published',
    title: 'External validation of SpineNetV2 on a comprehensive set of radiological features for grading lumbosacral disc pathologies',
    authors: 'Alemu Sisay Nigru MSc, Sergio Benini PhD, Matteo Bonetti MD, Graziella Bragaglio MSc, Michele Frigerio MD, Federico Maffezzoni MSc, Riccardo Leonardi PhD',
    journal: 'North American Spine Society Journal (NASSJ)',
    highlights: [
      'Retrospective analysis of 1747 lumbosacral IVDs from 353 patients; SpineNetV2 graded 11 distinct disc pathologies.',
      'Strong performance with high agreement (Cohen\'s Kappa, Lin\'s Concordance, MCC > 0.7) for most pathologies.',
      'Lower agreement for foraminal stenosis and disc herniation—underscores limitations of sagittal MR images for these conditions.',
    ],
    abstract: 'Background: In recent years, the integration of Artificial Intelligence (AI) models has revolutionized the diagnosis of Low Back Pain (LBP) and associated disc pathologies. Among these, SpineNetV2 stands out as a state-of-the-art, open-access model for detecting and grading various intervertebral disc pathologies. However, ensuring the reliability and applicability of AI models like SpineNetV2 is paramount. Rigorous validation is essential to guarantee their robustness and generalizability across diverse patient cohorts and imaging protocols. Methods: We conducted a retrospective analysis of MRI images of 1747 lumbosacral intervertebral discs (IVDs) from 353 patients (mean age, 54 ± 15.4 years, 44.5% female) with various spinal disorders, collected between September 2021 and February 2023 at X-Ray Service s.r.l. The SpineNetV2 system was used to grade 11 distinct lumbosacral disc pathologies, including Pfirrmann grading, disc narrowing, central canal stenosis, spondylolisthesis, (upper and lower) endplate defects, (upper and lower) marrow changes, (right and left) foraminal stenosis, and disc herniation, using T2-weighted sagittal MR images. Performance metrics included accuracy, balanced accuracy, precision, F1 score, Matthew\'s Correlation Coefficient, Brier Score Loss, Lin\'s concordance correlation coefficients, and Cohen\'s kappa coefficients. Two expert radiologists provide annotations for these discs. The evaluation of SpineNetV2\'s grading is compared against expert radiologists\' assessments. Results: SpineNetV2 demonstrated strong performance across various metrics, with high agreement scores (Cohen\'s Kappa, Lin\'s Concordance, and Matthew\'s Correlation Coefficient exceeding 0.7) for most pathologies. However, lower agreement was found for foraminal stenosis and disc herniation, underscoring the limitations of sagittal MR images for evaluating these conditions. Conclusions: This study highlights the importance of external validation, emphasizing the need for comprehensive assessments of deep learning models. SpineNetV2 exhibits promising results in predicting disc pathologies, with findings guiding further improvements. The open-source release of SpineNetV2 enables researchers to independently validate and extend the model\'s capabilities. This collaborative approach promotes innovation and accelerates the development of more reliable and comprehensive deep learning tools for the assessment of spine pathology.',
    link: 'https://www.sciencedirect.com/science/article/pii/S2666548424002579',
  },
];
